eval "$(starship init zsh)"
alias config-i3="xed ~/.config/i3/config &"
alias config-polybar="xed ~/.config/polybar/config.ini &"
alias config-picom="xed ~/.config/picom/picom.conf &"
alias config-rofi="xed ~/.config/rofi/config.rasi &"
alias config-alacritty="xed ~/.config/alacritty/alacritty.toml &"
alias cs-game="wine ~/.wine/drive_c/Counter-Strike\ Original/Counter-Strike.exe"
