#!/bin/bash

# Load pywal colors
source "${HOME}/.cache/wal/colors.sh"

# Override with better bar colors
bar_bg="${color0}"           # Dark muted color
bar_fg="${color15}"          # Light text
inactive_ws_bg="${color8}"   # Inactive workspace color
urgent_bg="${color1}"        # Red or alert color

# Generate config snippet
cat > "${HOME}/.config/i3/wal-colors" <<EOF
# Auto-generated by wal
set \$bar-bg       ${bar_bg}
set \$bar-fg       ${bar_fg}
set \$inactive-bg  ${inactive_ws_bg}
set \$urgent-bg    ${urgent_bg}
EOF

# Reload i3
i3-msg reload
